function plotModelComparisonGCM(rmos_list, rbase_list)
% plotModelComparisonGCM - Plots accuracy vs level and ROC curves for 7 methods
%
% Inputs:
%   rmos_list  - 1x3 cell array of rmos structs for levels 50, 350, 9900
%   rbase_list - 1x3 cell array of rbase structs for the same levels

% --- Method definitions ---
methodNames = {
    'MOS-KL + SVM RBF 50', ...
    'MOS-KL + SVM RBF 350', ...
    'MOS-KL + SVM RBF 9900', ...
    'SVM RBF', ...
    'Gradient Boosting', ...
    'RUS Boost', ...
    'Random Forest'
};

colors = {
    [143 188 143]/255, ...
    [1 0.5 0.2], ...
    [30 144 255]/255, ...
    [0.5 0.5 0.5], ...
    [0 0 1], ...
    [1 0 1], ...
    [0 1 1]
};

lineStyles = {'-', '-', '-', '--', '--', '--', '--'};
markers = {'o', 'o', 'o', '', '', '', ''};

% we only need 3 sample sizes for this plot
rmos_list(3) = [];
rbase_list(3) = [];

% --- Levels and Accuracy and precisionA ---
num_levels = length(rmos_list{1}.accuracy);
levels = 0:(num_levels-1);

acc_all = [
    rmos_list{1}.accuracy;
    rmos_list{2}.accuracy;
    rmos_list{3}.accuracy
];

preA_all = [
    rmos_list{1}.PrecisionA;
    rmos_list{2}.PrecisionA;
    rmos_list{3}.PrecisionA
];

% --- For each baseline model, find best result across rbase_list ---
num_baselines = 4;
best_acc = zeros(num_baselines, num_levels);
%best_roc = cell(1, num_baselines);
best_preA = zeros(num_baselines, num_levels);

for m = 1:num_baselines
    %best_auc = -inf;
    temp_acc = -inf;
    for k = 1:length(rbase_list)
        acc = rbase_list{k}.accuracy(m);
        %auc = rbase_list{k}.AUC(m);
        if acc > temp_acc
            temp_acc = acc;
            best_acc(m,:) = repmat(rbase_list{k}.accuracy(m), 1, num_levels);
            best_preA(m,:) = repmat(rbase_list{k}.PrecisionA(m), 1, num_levels);
        end
        %if auc > best_auc
        %    best_auc = auc;
        %    best_roc{m} = rbase_list{k}.ROCs{m};
        %end
    end
end

% Append best baseline accuracies
acc_all = [acc_all; best_acc];
preA_all = [preA_all; best_preA];

% --- ROC curves ---
%rocs = {
%    rmos_list{1}.ROCs{6}, ...
%    rmos_list{2}.ROCs{6}, ...
%    rmos_list{3}.ROCs{6}, ...
%    best_roc{:}
%};

%--- Begin plotting ---
figure('Position', [100, 100, 1200, 500], 'Color', 'white');

%--- Left: Accuracy vs Level ---
subplot(1,2,1); hold on;
for i = 1:size(acc_all,1)
    if i <= 3
        plot(levels, acc_all(i,:), [lineStyles{i}, markers{i}], ...
            'Color', colors{i}, 'LineWidth', 2, ...
            'MarkerSize', 5, 'MarkerFaceColor', [1 1 1], ...
            'MarkerEdgeColor', colors{i}, 'DisplayName', methodNames{i});
    else
        yline(acc_all(i,1), lineStyles{i}, 'Color', colors{i}, ...
            'LineWidth', 2, 'DisplayName', methodNames{i});
    end
end

ylim([0 1])
axis square
legend('Location','southwest','Interpreter','latex','FontSize',15)
grid on;
set(gca, ...
  'Box'         , 'off'     , ...
  'TickDir'     , 'out'     , ...
  'TickLength'  , [.025 .025] , ...
  'XMinorTick'  , 'on'      , ...
  'YMinorTick'  , 'on'      , ...
  'XGrid'       , 'off'     , ...
  'YGrid'       , 'on'      , ...
  'XColor'      , [.3 .3 .3], ...
  'YColor'      , [.3 .3 .3], ...
  'YTick'       , 0:0.1:1   , ...
  'XTick'       , 0:1:8     , ...
  'LineWidth'   , 1         );
ax = gca;
ax.FontSize = 11;
ylabel('Overall Accuracy','Interpreter','latex','FontSize',16)
xlabel('\emph{Level}','Interpreter','latex','FontSize',16)

%--- Right: PrecisionA vs Level ---
subplot(1,2,2); hold on;
for i = 1:size(acc_all,1)
    if i <= 3
        plot(levels, preA_all(i,:), [lineStyles{i}, markers{i}], ...
            'Color', colors{i}, 'LineWidth', 2, ...
            'MarkerSize', 5, 'MarkerFaceColor', [1 1 1], ...
            'MarkerEdgeColor', colors{i}, 'DisplayName', methodNames{i});
    else
        yline(preA_all(i,1), lineStyles{i}, 'Color', colors{i}, ...
            'LineWidth', 2, 'DisplayName', methodNames{i});
    end
end

ylim([0 1])
axis square
grid on;
set(gca, ...
  'Box'         , 'off'     , ...
  'TickDir'     , 'out'     , ...
  'TickLength'  , [.025 .025] , ...
  'XMinorTick'  , 'on'      , ...
  'YMinorTick'  , 'on'      , ...
  'XGrid'       , 'off'     , ...
  'YGrid'       , 'on'      , ...
  'XColor'      , [.3 .3 .3], ...
  'YColor'      , [.3 .3 .3], ...
  'YTick'       , 0:0.1:1   , ...
  'XTick'       , 0:1:8     , ...
  'LineWidth'   , 1         );
ax = gca;
ax.FontSize = 11;
ylabel('Precision','Interpreter','latex','FontSize',16)
xlabel('\emph{Level}','Interpreter','latex','FontSize',16)



% --- Right: Raw ROC Curves ---
%subplot(1,2,2); hold on;
%for i = 1:length(rocs)
%    plot(rocs{i}(:,1), rocs{i}(:,2), lineStyles{i}, ...
%        'Color', colors{i}, 'LineWidth', 2, ...
%        'DisplayName', methodNames{i});
%end

%xlim([0 1]); ylim([0 1]);
%axis square
%grid on;
%set(gca, ...
%  'Box'         , 'off'     , ...
%  'TickDir'     , 'out'     , ...  'TickLength'  , [.025 .025] , ...
%  'XMinorTick'  , 'on'      , ...
%  'YMinorTick'  , 'on'      , ...
%  'XGrid'       , 'off'     , ...
%  'YGrid'       , 'on'      , ...
%  'XColor'      , [.3 .3 .3], ...
%  'YColor'      , [.3 .3 .3], ...
%  'YTick'       , 0:0.1:1   , ...
%  'LineWidth'   , 1         );
%ax = gca;
%ax.FontSize = 11;
%ylabel('True Positive Rate','Interpreter','latex','FontSize',14)
%xlabel('\emph{False Positive Rate}','Interpreter','latex','FontSize',14)

%exportgraphics(gcf, 'GCMsin20model.pdf', 'ContentType', 'vector');

end
