function plotSampleComparisonGCM(rmos_list, rbase_list)
% plotSampleComparisonGCM - Plots accuracy and AUC vs sample size for MOS-KL and 4 baselines
%
% Inputs:
%   rmos_list   - cell array {r50, r350, r9900}, each with .accuracy and .AUC (MOS-KL)
%   rbase_list  - cell array {rbase50, rbase350, rbase9900}, each with .accuracy and .AUC
%                 where baseline .accuracy and .AUC are vectors [SVM, GB, RUS, RF]

% Method labels
methodNames = {
    'MOS-KL + SVM RBF', ...
    'SVM RBF', ...
    'Gradient Boosting', ...
    'RUS Boost', ...
    'Random Forest'
};

colors = {
    [143 188 143]/255, ...
    [143 188 143]/255, ...
    [30 144 255]/255, ...
    [0.5 0.5 0.5], ...
    [0 0 1]
};

lineStyles = {'-', '--', '--', '--', '--'};
markers = {'o', 'o', 'o', 'o', 'o'};

% --- Define sample sizes (same order as input) ---
sample_sizes = [50, 350, 1500, 9900];

% --- Extract accuracy and AUC data ---
num_points = numel(rmos_list);
acc_matrix = zeros(5, num_points);
%auc_matrix = zeros(5, num_points);

for i = 1:num_points
    % MOS-KL: take 6th value of accuracy and AUC
    acc_matrix(1, i) = rmos_list{i}.accuracy(7);
    %auc_matrix(1, i) = rmos_list{i}.AUC(7);
    preA_matrix(1, i) = rmos_list{i}.PrecisionA(7);

    % Baseline: assume accuracy and AUC vectors of [SVM, GB, RUS, RF]
    acc_matrix(2, i) = rbase_list{i}.accuracy(1);  % WSVM
    acc_matrix(3, i) = rbase_list{i}.accuracy(2);  % GB
    acc_matrix(4, i) = rbase_list{i}.accuracy(3);  % RUS
    acc_matrix(5, i) = rbase_list{i}.accuracy(4);  % RF

    preA_matrix(2, i) = rbase_list{i}.PrecisionA(1);  % WSVM
    preA_matrix(3, i) = rbase_list{i}.PrecisionA(2);  % GB
    preA_matrix(4, i) = rbase_list{i}.PrecisionA(3);  % RUS
    preA_matrix(5, i) = rbase_list{i}.PrecisionA(4);  % RF
    %auc_matrix(2, i) = rbase_list{i}.AUC(1);
    %auc_matrix(3, i) = rbase_list{i}.AUC(2);
    %auc_matrix(4, i) = rbase_list{i}.AUC(3);
    %auc_matrix(5, i) = rbase_list{i}.AUC(4);
end

% --- Begin Plotting ---
figure('Position', [100, 100, 1200, 500], 'Color', 'white');

% --- Left subplot: Accuracy vs Samples ---
subplot(1,2,1); hold on;
for i = 1:5
    plot(sample_sizes, acc_matrix(i,:), ...
        [lineStyles{i}, markers{i}], ...
        'Color', colors{i}, 'LineWidth', 2, ...
        'MarkerSize', 5, ...
        'MarkerEdgeColor', colors{i}, ...
        'MarkerFaceColor', [1 1 1], ...
        'DisplayName', methodNames{i});
end
%set(gca, 'XScale', 'log');

ylim([0 1])
axis square
legend('Location','southwest','Interpreter','latex','FontSize',15)
grid on;
set(gca, ...
  'XScale'      , 'log'     , ...
  'Box'         , 'off'     , ...
  'TickDir'     , 'out'     , ...
  'TickLength'  , [.025 .025] , ...
  'XMinorTick'  , 'on'      , ...
  'YMinorTick'  , 'on'      , ...
  'XGrid'       , 'off'     , ...
  'YGrid'       , 'on'      , ...
  'XColor'      , [.3 .3 .3], ...
  'YColor'      , [.3 .3 .3], ...
  'YTick'       , 0:0.1:1   , ...
  'LineWidth'   , 1         );
ax = gca;
ax.FontSize = 11;

xlabel('Samples','Interpreter','latex','FontSize',16)
ylabel('Overall Accuracy','Interpreter','latex','FontSize',16)
%ylim([0 1]); axis square
%legend('Location','southwest','Interpreter','latex','FontSize',12)
%set(gca, ...
%  'Box','off', 'TickDir','out', 'TickLength',[.025 .025], ...
%  'XMinorTick','on', 'YMinorTick','on', 'YGrid','on', ...
%  'XColor',[.3 .3 .3], 'YColor',[.3 .3 .3], 'YTick',0:0.1:1, 'LineWidth',1);

% --- Right subplot: PrecisionA vs Samples ---
subplot(1,2,2); hold on;
for i = 1:5
    plot(sample_sizes, preA_matrix(i,:), ...
        [lineStyles{i}, markers{i}], ...
        'Color', colors{i}, 'LineWidth', 2, ...
        'MarkerSize', 5, ...
        'MarkerEdgeColor', colors{i}, ...
        'MarkerFaceColor', [1 1 1], ...
        'DisplayName', methodNames{i});
end
%set(gca, 'XScale', 'log');

ylim([0 1])
axis square
grid on;
set(gca, ...
  'XScale'      , 'log'     , ...
  'Box'         , 'off'     , ...
  'TickDir'     , 'out'     , ...
  'TickLength'  , [.025 .025] , ...
  'XMinorTick'  , 'on'      , ...
  'YMinorTick'  , 'on'      , ...
  'XGrid'       , 'off'     , ...
  'YGrid'       , 'on'      , ...
  'XColor'      , [.3 .3 .3], ...
  'YColor'      , [.3 .3 .3], ...
  'YTick'       , 0:0.1:1   , ...
  'LineWidth'   , 1         );
ax = gca;
ax.FontSize = 11;

xlabel('Samples','Interpreter','latex','FontSize',16)
ylabel('Precision','Interpreter','latex','FontSize',16)

% --- Right subplot: AUC vs Samples ---
%subplot(1,2,2); hold on;
%for i = 1:5
%    plot(sample_sizes, auc_matrix(i,:), ...
%        [lineStyles{i}, markers{i}], ...
%        'Color', colors{i}, 'LineWidth', 2, ...
%        'MarkerSize', 5, ...
%        'MarkerEdgeColor', colors{i}, ...
%        'MarkerFaceColor', [1 1 1], ...
%        'DisplayName', methodNames{i});
%end
%set(gca, 'XScale', 'log');

%ylim([0 1])
%axis square
%grid on;
%set(gca, ...
%  'XScale'      , 'log'     , ...
%  'Box'         , 'off'     , ...
%  'TickDir'     , 'out'     , ...
%  'TickLength'  , [.025 .025] , ...
%  'XMinorTick'  , 'on'      , ...
%  'YMinorTick'  , 'on'      , ...
%  'XGrid'       , 'off'     , ...
%  'YGrid'       , 'on'      , ...
%  'XColor'      , [.3 .3 .3], ...
%  'YColor'      , [.3 .3 .3], ...
%  'YTick'       , 0:0.1:1   , ...
%  'LineWidth'   , 1         );
%ax = gca;
%ax.FontSize = 11;

%xlabel('Samples','Interpreter','latex','FontSize',14)
%ylabel('AUC','Interpreter','latex','FontSize',14)
%ylim([0 1]); axis square
%set(gca, ...
%  'Box','off', 'TickDir','out', 'TickLength',[.025 .025], ...
%  'XMinorTick','on', 'YMinorTick','on', 'YGrid','on', ...
%  'XColor',[.3 .3 .3], 'YColor',[.3 .3 .3], 'YTick',0:0.1:1, 'LineWidth',1);

% --- Export to PDF ---
%exportgraphics(gcf, 'GCMsin20sample.pdf', 'ContentType', 'vector');

end
